name: Node Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      with: 
        node-version: 12
      - run: npm ci # <-> npm install
      - run: npm test # test code
      - run: npm run build # see if build completes
      